### ISSUE TITLE
[BUG]:  Unable to install ... problems with Six (multiple versions)

### ISSUE THREAD

**Issue by simonegiusti** [Tyfy/OctoPrint-TapoSmartplug#11]
Hello,
I am not able to install this plugin on Octoprint ...

this is the log:

`Installing plugin...
Installing plugin from https://github.com/Tyfy/OctoPrint-TapoSmartplug/archive/master.zip...
/home/simone/OctoPrint/venv/bin/python3 -m pip --disable-pip-version-check install file:///tmp/tmpoufyau4a/OctoPrint-TapoSmartplug-master.zip --no-cache-dir
Processing /tmp/tmpoufyau4a/OctoPrint-TapoSmartplug-master.zip
Requirement already satisfied: OctoPrint in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint-TapoSmartplug==0.0.1) (1.7.0)
Collecting PyP100
Downloading PyP100-0.0.13.tar.gz (4.5 kB)
Requirement already satisfied: uptime in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint-TapoSmartplug==0.0.1) (3.0.1)
Requirement already satisfied: Click<8,>=7.1.2 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (7.1.2)
Requirement already satisfied: Flask-Assets<3,>=2.0 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (2.0)
Requirement already satisfied: Flask-Babel<2,>=1.0 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (1.0.0)
Requirement already satisfied: Flask-Login<0.6,>=0.5 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (0.5.0)
Requirement already satisfied: Jinja2<3,>=2.11.3 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (2.11.3)
Requirement already satisfied: OctoPrint-FileCheck>=2021.2.23 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (2021.2.23)
Requirement already satisfied: OctoPrint-FirmwareCheck>=2021.10.11 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (2021.10.11)
Requirement already satisfied: OctoPrint-PiSupport>=2021.8.2 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (2021.8.2)
Requirement already satisfied: PyYAML<6,>=5.4.1 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (5.4.1)
Requirement already satisfied: blinker<2,>=1.4 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (1.4)
Requirement already satisfied: cachelib<0.2,>=0.1 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (0.1.1)
Requirement already satisfied: emoji<2,>=1.4.2 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (1.6.1)
Requirement already satisfied: filetype<2,>=1.0.7 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (1.0.7)
Requirement already satisfied: flask<2,>=1.1.4 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (1.1.4)
Requirement already satisfied: future<1,>=0.18.2 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (0.18.2)
Requirement already satisfied: itsdangerous<2,>=1.1.0 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (1.1.0)
Requirement already satisfied: markdown<3.2,>=3.1 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (3.1.1)
Requirement already satisfied: markupsafe<2.0,>=1.1 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (1.1.1)
Requirement already satisfied: netaddr<0.9,>=0.8 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (0.8.0)
Requirement already satisfied: netifaces<1,>=0.11 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (0.11.0)
Requirement already satisfied: pkginfo<2,>=1.7.1 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (1.7.1)
Requirement already satisfied: psutil<6,>=5.8 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (5.8.0)
Requirement already satisfied: pylru<2,>=1.2 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (1.2.0)
Requirement already satisfied: pyserial<4,>=3.4 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (3.5)
Requirement already satisfied: regex!=2018.11.6 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (2020.11.13)
Requirement already satisfied: requests<3,>=2.26.0 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (2.26.0)
Requirement already satisfied: sarge==0.1.6 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (0.1.6)
Requirement already satisfied: semantic_version<3,>=2.8.5 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (2.8.5)
Requirement already satisfied: sentry-sdk<2,>=1.3.1 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (1.4.3)
Requirement already satisfied: watchdog==0.10.4 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (0.10.4)
Requirement already satisfied: websocket-client<1,>=0.59 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (0.59.0)
Requirement already satisfied: werkzeug<2,>=1.0.1 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (1.0.1)
Requirement already satisfied: wrapt<1.13,>=1.12.1 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (1.12.1)
Requirement already satisfied: zipstream-new<1.2,>=1.1.8 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (1.1.8)
Requirement already satisfied: colorlog<6,>=5.0.1 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (5.0.1)
Requirement already satisfied: feedparser<7,>=6.0.8 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (6.0.8)
Requirement already satisfied: immutabledict<3,>=2.1 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (2.2.1)
Requirement already satisfied: pathvalidate<3,>=2.4.1 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (2.5.0)
Requirement already satisfied: tornado<7,>=6 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (6.1)
Requirement already satisfied: unidecode in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (0.4.21)
Requirement already satisfied: zeroconf<0.34,>=0.33 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (0.33.4)
Requirement already satisfied: pathtools>=0.1.1 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from watchdog==0.10.4->OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (0.1.2)
Requirement already satisfied: sgmllib3k in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from feedparser<7,>=6.0.8->OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (1.0.0)
Requirement already satisfied: webassets>=2.0 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from Flask-Assets<3,>=2.0->OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (2.0)
Requirement already satisfied: pytz in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (2021.1)
Requirement already satisfied: Babel>=2.3 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (2.9.0)
Requirement already satisfied: setuptools>=36 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from markdown<3.2,>=3.1->OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (39.0.1)
Requirement already satisfied: importlib-resources in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from netaddr<0.9,>=0.8->OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (5.1.1)
Requirement already satisfied: idna<4,>=2.5 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from requests<3,>=2.26.0->OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from requests<3,>=2.26.0->OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (1.26.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from requests<3,>=2.26.0->OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (2020.12.5)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from requests<3,>=2.26.0->OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (2.0.7)
Requirement already satisfied: six in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from websocket-client<1,>=0.59->OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (1.15.0)
Requirement already satisfied: ifaddr>=0.1.7 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from zeroconf<0.34,>=0.33->OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (0.1.7)
Requirement already satisfied: zipp>=0.4 in /home/simone/OctoPrint/venv/lib/python3.6/site-packages (from importlib-resources->netaddr<0.9,>=0.8->OctoPrint->OctoPrint-TapoSmartplug==0.0.1) (3.4.0)
Collecting pkcs7==0.1.2
Downloading pkcs7-0.1.2.zip (3.3 kB)
Collecting pycryptodome==3.9.8
Downloading pycryptodome-3.9.8-cp36-cp36m-manylinux1_i686.whl (13.7 MB)
Collecting PyP100
Downloading PyP100-0.0.12.tar.gz (4.5 kB)
Downloading PyP100-0.0.11.tar.gz (4.5 kB)
Downloading PyP100-0.0.10.tar.gz (4.2 kB)
ERROR: Command errored out with exit status 1:
command: /home/simone/OctoPrint/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lztalymr/pyp100_1f6c1b277f9a4e36b243459fd987d273/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lztalymr/pyp100_1f6c1b277f9a4e36b243459fd987d273/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-y2zw82my
cwd: /tmp/pip-install-lztalymr/pyp100_1f6c1b277f9a4e36b243459fd987d273/
Complete output (5 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-lztalymr/pyp100_1f6c1b277f9a4e36b243459fd987d273/setup.py", line 6, in <module>
with open('HISTORY.md') as history_file:
FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.md'
----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d2/cb/58b3913adfb7515bf04721f8c31f210925d74cd191d723d24ec785521e3e/PyP100-0.0.10.tar.gz#sha256=01db3b02e918ea9a674f25d4505ef705d9be23a37043ed322fe5f4612766bea8 (from https://pypi.org/simple/pyp100/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Downloading PyP100-0.0.9-py3-none-any.whl (5.4 kB)
Downloading PyP100-0.0.8-py3-none-any.whl (5.3 kB)
Downloading PyP100-0.0.7-py3-none-any.whl (5.3 kB)
Downloading PyP100-0.0.6-py3-none-any.whl (5.3 kB)
Downloading PyP100-0.0.5-py3-none-any.whl (5.3 kB)
Downloading PyP100-0.0.4-py3-none-any.whl (5.3 kB)
Downloading PyP100-0.0.3-py3-none-any.whl (4.9 kB)
Downloading PyP100-0.0.2-py3-none-any.whl (4.8 kB)
Downloading PyP100-0.0.1-py3-none-any.whl (4.5 kB)
INFO: pip is looking at multiple versions of zipp to determine which version is compatible with other requirements. This could take a while.
Collecting zipp>=0.4
Downloading zipp-3.6.0-py3-none-any.whl (5.3 kB)
Downloading zipp-3.5.1-py3-none-any.whl (5.3 kB)
Downloading zipp-3.5.0-py3-none-any.whl (5.7 kB)
Downloading zipp-3.4.2-py3-none-any.whl (5.3 kB)
Downloading zipp-3.4.1-py3-none-any.whl (5.2 kB)
Downloading zipp-3.3.2-py3-none-any.whl (5.2 kB)
Downloading zipp-3.3.1-py3-none-any.whl (5.3 kB)
Downloading zipp-3.3.0-py3-none-any.whl (5.3 kB)
Downloading zipp-3.2.0-py3-none-any.whl (5.1 kB)
Downloading zipp-3.1.0-py3-none-any.whl (4.9 kB)
Downloading zipp-3.0.0-py3-none-any.whl (4.8 kB)
Downloading zipp-2.2.1-py3-none-any.whl (4.6 kB)
Downloading zipp-2.2.0-py36-none-any.whl (4.6 kB)
Downloading zipp-2.1.0-py3-none-any.whl (4.6 kB)
Downloading zipp-2.0.1-py3-none-any.whl (4.1 kB)
Downloading zipp-2.0.0-py3-none-any.whl (4.2 kB)
Downloading zipp-1.2.0-py2.py3-none-any.whl (4.8 kB)
Downloading zipp-1.1.1-py2.py3-none-any.whl (4.6 kB)
Downloading zipp-1.1.0-py2.py3-none-any.whl (4.6 kB)
Downloading zipp-1.0.0-py2.py3-none-any.whl (4.1 kB)
Downloading zipp-0.6.0-py2.py3-none-any.whl (4.1 kB)
Downloading zipp-0.5.2-py2.py3-none-any.whl (3.8 kB)
Downloading zipp-0.5.1-py2.py3-none-any.whl (3.8 kB)
Downloading zipp-0.5.0-py2.py3-none-any.whl (3.7 kB)
Downloading zipp-0.4.0-py2.py3-none-any.whl (3.4 kB)
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of zipp to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
Collecting more-itertools
Downloading more_itertools-8.10.0-py3-none-any.whl (51 kB)
INFO: pip is looking at multiple versions of more-itertools to determine which version is compatible with other requirements. This could take a while.
Downloading more_itertools-8.9.0-py3-none-any.whl (51 kB)
Downloading more_itertools-8.8.0-py3-none-any.whl (48 kB)
Downloading more_itertools-8.7.0-py3-none-any.whl (48 kB)
Downloading more_itertools-8.6.0-py3-none-any.whl (45 kB)
Downloading more_itertools-8.5.0-py3-none-any.whl (44 kB)
Downloading more_itertools-8.4.0-py3-none-any.whl (43 kB)
Downloading more_itertools-8.3.0-py3-none-any.whl (44 kB)
Downloading more_itertools-8.2.0-py3-none-any.whl (43 kB)
Downloading more_itertools-8.1.0-py3-none-any.whl (41 kB)
Downloading more_itertools-8.0.2-py3-none-any.whl (40 kB)
Downloading more_itertools-8.0.1-py3-none-any.whl (40 kB)
Downloading more_itertools-8.0.0-py3-none-any.whl (40 kB)
Downloading more_itertools-7.2.0-py3-none-any.whl (57 kB)
Downloading more_itertools-7.1.0-py3-none-any.whl (55 kB)
Downloading more_itertools-7.0.0-py3-none-any.whl (53 kB)
Downloading more_itertools-6.0.0-py3-none-any.whl (52 kB)
Downloading more_itertools-5.0.0-py3-none-any.whl (52 kB)
Downloading more_itertools-4.3.0-py3-none-any.whl (48 kB)
Downloading more_itertools-4.2.0-py3-none-any.whl (45 kB)
Downloading more_itertools-4.1.0-py3-none-any.whl (47 kB)
Downloading more_itertools-4.0.1-py3-none-any.whl (44 kB)
Downloading more_itertools-4.0.0-py3-none-any.whl (44 kB)
Downloading more_itertools-3.2.0-py3-none-any.whl (39 kB)
Downloading more_itertools-3.1.0-py3-none-any.whl (37 kB)
Downloading more_itertools-3.0.0-py3-none-any.whl (34 kB)
Downloading more_itertools-2.6.0-py3-none-any.whl (33 kB)
Downloading more_itertools-2.5.0-py3-none-any.whl (28 kB)
Downloading more-itertools-2.4.1.tar.gz (28 kB)
Downloading more-itertools-2.4.tar.gz (28 kB)
Downloading more-itertools-2.3.tar.gz (22 kB)
Downloading more-itertools-2.2.tar.gz (19 kB)
Downloading more-itertools-2.1.tar.gz (19 kB)
Downloading more-itertools-2.0.tar.gz (13 kB)
Downloading more-itertools-1.1.tar.gz (12 kB)
Downloading more-itertools-1.0.tar.gz (4.3 kB)
INFO: pip is looking at multiple versions of more-itertools to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of six to determine which version is compatible with other requirements. This could take a while.
Collecting six
Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
Downloading six-1.13.0-py2.py3-none-any.whl (10 kB)
Downloading six-1.12.0-py2.py3-none-any.whl (10 kB)
Downloading six-1.11.0-py2.py3-none-any.whl (10 kB)
Downloading six-1.10.0-py2.py3-none-any.whl (10 kB)
Downloading six-1.9.0-py2.py3-none-any.whl (10 kB)
Downloading six-1.8.0-py2.py3-none-any.whl (9.7 kB)
Downloading six-1.7.3-py2.py3-none-any.whl (9.5 kB)
Downloading six-1.7.2-py2.py3-none-any.whl (9.6 kB)
Downloading six-1.7.1-py2.py3-none-any.whl (9.6 kB)
Downloading six-1.7.0-py2.py3-none-any.whl (9.3 kB)
Downloading six-1.6.1-py2.py3-none-any.whl (8.6 kB)
Downloading six-1.6.0-py2.py3-none-any.whl (8.5 kB)
Downloading six-1.5.2-py2.py3-none-any.whl (8.4 kB)
Downloading six-1.5.1-py2.py3-none-any.whl (8.4 kB)
Downloading six-1.5.0-py2.py3-none-any.whl (8.2 kB)
Downloading six-1.4.1.tar.gz (21 kB)
Downloading six-1.4.0.tar.gz (21 kB)
Downloading six-1.3.0.tar.gz (17 kB)
Downloading six-1.2.0.tar.gz (15 kB)
Downloading six-1.1.0.tar.gz (12 kB)
Downloading six-1.0.0.tar.gz (11 kB)
INFO: pip is looking at multiple versions of six to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking`

Octoprint log:
https://www.dropbox.com/s/l5it00rnbnq22p5/octoprint-systeminfo-20211017205718.zip?dl=0

**Comment by simonegiusti** [comment]
Solved with Octoprint 1.7.2
