### ISSUE TITLE
get error during install but says unkown plugin installed[BUG]: 

### ISSUE THREAD

**Issue by Doprintityourself** [Tyfy/OctoPrint-TapoSmartplug#4]
Here are the logs:
2021-02-15 18:33:49,966   /home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install file:///tmp/tmpte28Q0/master.zip --no-cache-dir
2021-02-15 18:33:52,001 > Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
2021-02-15 18:33:52,001 > Processing /tmp/tmpte28Q0/master.zip
2021-02-15 18:33:53,003 > Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint-TapoSmartplug==0.0.1) (1.5.3)
2021-02-15 18:33:54,005 > Collecting uptime
2021-02-15 18:33:54,005 > Downloading https://files.pythonhosted.org/packages/ad/53/6c420ddf6949097d6f9406358951c9322505849bea9cb79efe3acc0bb55d/uptime-3.0.1.tar.gz
2021-02-15 18:33:55,008 > Collecting PyP100
2021-02-15 18:33:55,009 > Downloading https://files.pythonhosted.org/packages/a1/33/510a209f3f0dcf6dbce309b667a9e3ebde0d5e8e4697cf16392b0cd42c1f/PyP100-0.0.11.tar.gz
2021-02-15 18:33:55,512 ! ERROR: Command errored out with exit status 1:
2021-02-15 18:33:55,512 ! command: /home/pi/oprint/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-GCDGfG/PyP100/setup.py'"'"'; __file__='"'"'/tmp/pip-install-GCDGfG/PyP100/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-GCDGfG/PyP100/pip-egg-info
2021-02-15 18:33:55,513 ! cwd: /tmp/pip-install-GCDGfG/PyP100/
2021-02-15 18:33:55,514 ! Complete output (6 lines):
2021-02-15 18:33:55,514 ! Traceback (most recent call last):
2021-02-15 18:33:55,515 ! File "<string>", line 1, in <module>
2021-02-15 18:33:55,515 ! File "/tmp/pip-install-GCDGfG/PyP100/setup.py", line 31
2021-02-15 18:33:55,515 ! setup(**setup_args, install_requires=install_requires)
2021-02-15 18:33:55,515 ! ^
2021-02-15 18:33:55,516 ! SyntaxError: invalid syntax
2021-02-15 18:33:55,516 ! ----------------------------------------
2021-02-15 18:33:55,516 ! ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Doprintityourself** [comment]
![image](https://user-images.githubusercontent.com/70262325/108197109-352a8700-711a-11eb-8198-9ce26754d438.png)

**Comment by MrBourrin** [comment]
Same thing, impossible to install the plugin via the link or zip file

**Comment by NpFaith** [comment]
I have the same problem. Can you help?

ERROR: Command errored out with exit status 1:command: /home/pi/oprint/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0e1Y0r/PyP100/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0e1Y0r/PyP100/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-0e1Y0r/PyP100/pip-egg-infocwd: /tmp/pip-install-0e1Y0r/PyP100/Complete output (6 lines):Traceback (most recent call last):File "<string>", line 1, in <module>File "/tmp/pip-install-0e1Y0r/PyP100/setup.py", line 31setup(**setup_args, install_requires=install_requires)^SyntaxError: invalid syntax----------------------------------------ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.Error!Could not parse output from pip, see plugin_pluginmanager_console.log for generated output


Thanks for your time

**Comment by NpFaith** [comment]
I follow this instructions and could now install the plug-in lets hope that i can use it now.

https://octoprint.org/blog/2020/09/10/upgrade-to-py3/
